AllCops:
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 250

Style/GlobalVars:
  AllowedVariables:
    - "$logger"

Metrics/ParameterLists:
  Max: 12

# our heredocs are carefully crafted and need to have no whitespace indentation
Layout/IndentHeredoc:
  Enabled: false

# Ignored just temporarily
Style/HashSyntax:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

# I need to learn a little more about this
Security/YAMLLoad:
  Enabled: false

# I also need to learn more about this
Style/EachWithObject:
  Enabled: false

# We're letting codeclimate do this analysis
Metrics/BlockNesting:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
