matrix:
  include:
    - os: linux
      name: Linux Unit Tests
      language: ruby
      rvm: 2.4.1
      cache: bundler
      script: bundle exec rake
    - os: linux
      name: Rubocop
      script: bundle exec rubocop lib
      language: ruby
      rvm: 2.4.1
      cache: bundler
    - os: osx
      name: Mac OSX Unit Tests
      language: ruby
      rvm: 2.4.1
      cache: bundler
      script: bundle exec rake
    - os: windows
      name: Windows Unit Tests
      language: cpp  # just a placeholder
      install:
        - ridk install
        - gem install bundler
        - bundle install
      script: bundle exec rake
after_script:
  - bundle exec rake coveralls:push
