language: ruby
rvm: 2.4.1
cache: bundler
matrix:
  include:
    - os: linux
      name: Linux Unit Tests
    - os: linux
      name: Rubocop
      script: bundle exec rubocop lib
    - os: osx
      name: Mac OSX Unit Tests
    # - os: windows  --  windows doesn't have language: ruby support yet
scripts:
  - bundle exec rspec spec
after_script:
  - bundle exec rake coveralls:push
