language: ruby
rvm: 2.4.1
cache: bundler
matrix:
  include:
    - os: linux
    - os: osx
    # - os: windows  --  windows doesn't have language: ruby support yet
#before_install:
#  - gem install bundler
scripts:
  - bundle exec rspec spec
after_script:
  - rake coveralls:push
